<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- the copy of robot_core_1 urdf -->
    <xacro:macro name="diffbot" params="prefix">
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="lidar.xacro" />
    <xacro:include filename="depth_camera.xacro"/>
    
    <xacro:property name="chassis_length" value="1.3501" />
    <xacro:property name="chassis_to_base_link" value="0.73595" />
    <xacro:property name="profile_height" value="0.0254" />
    <xacro:property name="profile_width" value="0.0254" />
    <xacro:property name="tower_height" value="0.508" />
    
    <xacro:property name="wheel_radius" value="0.1778" />
    <xacro:property name="wheel_thickness" value="0.07" />
    <xacro:property name="wheel_mass" value="0.05" />
    
    <xacro:property name="front_wheel_offset_x" value="0.3876" />
    <xacro:property name="back_wheel_offset_x" value="0.437" />
    
    <xacro:property name="wheel_offset_y" value="0.3182" />
    <xacro:property name="wheel_offset_z" value="0.1778" />
    <xacro:property name="caster_wheel_mass" value="0.01"/>


    <!-- BASE LINK -->

    <link name="base_link">

    </link>
    
    
    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="base_footprint"/>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="base_footprint">
    </link>
    
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="imu_link" />
    
    <!-- CHASSIS LONG BASE LEFT -->
    <!-- Needs to be 1.35m long, to the left by 0.2604m -->

    <joint name="chassis_base_left" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_base_left"/>
        <origin xyz="${chassis_to_base_link} -0.2604 0"/>
    </joint>

    <link name="chassis_base_left">
        <visual>
            <origin xyz="${-chassis_length/2} 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.0508 ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${-chassis_length/2} 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.0508 ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${-chassis_length}" y="0.0508" z="${profile_height}">
            <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_base_left">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <!-- CHASSIS LONG BASE RIGHT -->
    <!-- Needs to be 1.35m long, to the left by  -->

    <joint name="chassis_base_right" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_base_right"/>
        <origin xyz="${chassis_to_base_link} 0.2604 0"/>
    </joint>

    <link name="chassis_base_right">
        <visual>
            <origin xyz="${-chassis_length/2} 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.0508 ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${-chassis_length/2} 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.0508 ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${-chassis_length}" y="0.0508" z="${profile_height}">
            <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_base_right">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    
    <!-- TOWER BASE -->

    <joint name="tower_base_" type="fixed">
        <parent link="base_link"/>
        <child link="tower_base"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="tower_base">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${profile_width}" y="0.4702" z="${profile_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="tower_base">
        <material>Gazebo/White</material>
    </gazebo>
    


    <!-- TOWER HEIGHT LEFT -->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_up_left" type="fixed">
        <parent link="base_link"/>
        <child link="tower_up_left"/>
        <origin xyz="0 -0.2478 0"/>
    </joint>

    <link name="tower_up_left">
        <visual>
            <origin xyz="0 0 ${tower_height/2}"/>
            <geometry>
                <box size="${profile_width} ${profile_width} ${tower_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${tower_height/2}"/>
            <geometry>
                <box size="${profile_width} ${profile_width} ${tower_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${profile_width}" y="${profile_width}" z="${tower_height}">
            <origin xyz="0 0 ${tower_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="tower_up_left">
        <material>Gazebo/White</material>
    </gazebo>
    

    
    <!-- TOWER HEIGHT RIGHT-->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_up_right" type="fixed">
        <parent link="base_link"/>
        <child link="tower_up_right"/>
        <origin xyz="0 0.2478 0"/>
    </joint>

    <link name="tower_up_right">
        <visual>
            <origin xyz="0 0 ${tower_height/2}"/>
            <geometry>
                <box size="${profile_width} ${profile_width} ${tower_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${tower_height/2}"/>
            <geometry>
                <box size="${profile_width} ${profile_width} ${tower_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${profile_width}" y="${profile_width}" z="${tower_height}">
            <origin xyz="0 0 ${tower_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="tower_up_right">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <!-- TOWER TOP -->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_top" type="fixed">
        <parent link="base_link"/>
        <child link="tower_top"/>
        <origin xyz="0 0 ${tower_height-profile_width}"/>
    </joint>

    <link name="tower_top">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height*2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height*2}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${profile_width}" y="0.4702" z="${profile_height*2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    
    <!-- TOWER SUPPORT LEFT -->

    <joint name="tower_support_left" type="fixed">
        <parent link="base_link"/>
        <child link="tower_support_left"/>
        <origin xyz="-0.15635 -0.2478 0.160" rpy="0 ${-pi/4} 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="tower_support_left">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.4572 ${profile_width} ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.4572 ${profile_width} ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.4572" y="${profile_width}" z="${profile_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="tower_support_left">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <!-- TOWER SUPPORT RIGHT -->

    <joint name="tower_support_right" type="fixed">
        <parent link="base_link"/>
        <child link="tower_support_right"/>
        <origin xyz="-0.15635 0.2478 0.160" rpy="0 ${-pi/4} 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="tower_support_right">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.4572 ${profile_width} ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.4572 ${profile_width} ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.4572" y="${profile_width}" z="${profile_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="tower_support_right">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    
    <!-- MOTOR BASE FRONT -->

    <joint name="motor_base_front" type="fixed">
        <parent link="base_link"/>
        <child link="motor_base_front"/>
        <origin xyz="0.426 0 0"/>
    </joint>

    <link name="motor_base_front">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${profile_width}" y="0.4702" z="${profile_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="motor_base_front">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <!-- MOTOR BASE BACK -->

    <joint name="motor_base_back" type="fixed">
        <parent link="base_link"/>
        <child link="motor_base_back"/>
        <origin xyz="0.35 0 0"/>
    </joint>

    <link name="motor_base_back">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${profile_width} 0.4702 ${profile_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${profile_width}" y="0.4702" z="${profile_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="motor_base_back">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    
    <!-- MOTOR AND GEARBOX LINK -->

    <joint name="motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="motor"/>
        <origin xyz="0.3879 0 0"/>
    </joint>

    <link name="motor">
        <visual>
            <origin xyz="0 0 0.0375"/>
            <geometry>
                <box size="0.2 0.5 0.075"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.0375"/>
            <geometry>
                <box size="0.2 0.5 0.075"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.01" x="0.2" y="0.5" z="0.075">
            <origin xyz="0 0 0.0375" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="motor">
        <material>Gazebo/Orange</material>
    </gazebo>
    


    <!-- FRONT LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="${front_wheel_offset_x} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <surface>
                <friction>
                    <torsional>
                        <coefficient>1.0</coefficient>
                        <use_patch_radius>false</use_patch_radius>
                        <surface_radius>${wheel_radius}</surface_radius>
                    </torsional>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- FRONT RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${front_wheel_offset_x} -${wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <surface>
                <friction>
                    <torsional>
                        <coefficient>1.0</coefficient>
                        <use_patch_radius>false</use_patch_radius>
                        <surface_radius>${wheel_radius}</surface_radius>
                    </torsional>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    
    <!-- BACK LEFT WHEEL LINK -->

    <joint name="back_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_left_wheel"/>
        <origin xyz="-${back_wheel_offset_x} -${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="back_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <friction>
                <torsional>
                    <coefficient>1.0</coefficient>
                    <use_patch_radius>false</use_patch_radius>
                    <surface_radius>${wheel_radius}</surface_radius>
                </torsional>
            </friction>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <gazebo reference="back_left_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    
    <!-- BACK RIGHT WHEEL LINK -->

    <joint name="back_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_right_wheel"/>
        <origin xyz="-${back_wheel_offset_x} ${wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="back_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <friction>
                <torsional>
                    <coefficient>1.0</coefficient>
                    <use_patch_radius>false</use_patch_radius>
                    <surface_radius>${wheel_radius}</surface_radius>
                </torsional>
            </friction>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="back_right_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    </xacro:macro>  
     
</robot>
