<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:property name="chassis_length" value="1.3501" />
    <xacro:property name="chassis_to_base_link" value="0.4954" />
    <xacro:property name="profile_height" value="0.0254" />
    <xacro:property name="profile_width" value="0.0254" />
    <xacro:property name="tower_height" value="0.388" />
    
    <xacro:property name="wheel_radius" value="0.1778" />
    <xacro:property name="wheel_thickness" value="0.07" />
    <xacro:property name="wheel_mass" value="56" />
    
    <xacro:property name="front_wheel_offset_x" value="0.14" />
    <xacro:property name="back_wheel_offset_x" value="0.49" />
    
    <xacro:property name="wheel_offset_y" value="0.3182" />
    <xacro:property name="wheel_offset_z" value="0.1778" />
    <xacro:property name="caster_wheel_mass" value="56"/>

    <xacro:property name="double_prof_mass" value="0.235398773"/>
    <xacro:property name="single_prof_mass" value="0.147601476"/>
    <xacro:property name="spoke_mass" value="1.6"/>
    <xacro:property name="motorgearbox_mass" value="136"/>
    <xacro:property name="scoop_mass" value="196"/>
    <xacro:property name="tiltingact_mass" value="38"/>
    <xacro:property name="liftingact_mass" value="44"/>


    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.10045 0 ${tower_height-profile_width +profile_height*2 }" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>1
    </link>



    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>
