<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:property name="chassis_length" value="1.3501" />
    <xacro:property name="chassis_to_base_link" value="0.4954" />
    <xacro:property name="profile_height" value="0.0254" />
    <xacro:property name="profile_width" value="0.0254" />
    <xacro:property name="tower_height" value="0.388" />
    
    <xacro:property name="wheel_radius" value="0.1778" />
    <xacro:property name="wheel_thickness" value="0.07" />
    <xacro:property name="wheel_mass" value="56" />
    
    <xacro:property name="front_wheel_offset_x" value="0.14" />
    <xacro:property name="back_wheel_offset_x" value="0.49" />
    
    <xacro:property name="wheel_offset_y" value="0.3182" />
    <xacro:property name="wheel_offset_z" value="0.1778" />
    <xacro:property name="caster_wheel_mass" value="56"/>

    <xacro:property name="double_prof_mass" value="0.235398773"/>
    <xacro:property name="single_prof_mass" value="0.147601476"/>
    <xacro:property name="spoke_mass" value="1.6"/>
    <xacro:property name="motorgearbox_mass" value="136"/>
    <xacro:property name="scoop_mass" value="196"/>
    <xacro:property name="tiltingact_mass" value="38"/>
    <xacro:property name="liftingact_mass" value="44"/>
    <xacro:property name="M_PI" value="3.1415926535897931"/>


    <joint name="vlp16_base_mount_joint" type="fixed">
      <parent link="base_link"/>
      <child link="vlp16_base_link"/>
      <origin xyz="0.10045 0 ${tower_height-profile_width +profile_height*2 +0.06 }" rpy="0 0 0"/>

    </joint>

    <link name="vlp16_base_link">
      <inertial>
        <mass value="0.83"/>
        <origin xyz="0 0 0.03585"/>
        <inertia ixx="${(0.83 * (3.0*0.0516*0.0516 + 0.0717*0.0717)) / 12.0}" ixy="0" ixz="0" iyy="${(0.83 * (3.0*0.0516*0.0516 + 0.0717*0.0717)) / 12.0}" iyz="0" izz="${0.5 * 0.83 * (0.0516*0.0516)}"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="file://$(find ros_phoenix)/meshes/VLP16_base_1.dae"/>
        </geometry>
      </visual>
      <visual>
        <geometry>
          <mesh filename="file://$(find ros_phoenix)/meshes/VLP16_base_2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.03585"/>
        <geometry>
          <cylinder radius="0.0516" length="0.0717"/>
        </geometry>
      </collision>
    </link>

    <joint name="vlp16_base_scan_joint" type="fixed" >
      <origin xyz="0 0 0.0377" rpy="0 0 0" />
      <parent link="vlp16_base_link" />
      <child link="vlp16"/>
    </joint>

    <link name="vlp16">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.0377" />
        <geometry>
          <mesh filename="file://$(find ros_phoenix)/meshes/VLP16_scan.dae" />
        </geometry>
      </visual>
    </link>


    <gazebo reference="vlp16">
        <material>Gazebo/Red</material>

        <sensor name="VLP16" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
          <ray>
            <scan>
              <horizontal>
                <samples>1875</samples>
                <resolution>1</resolution>
                <min_angle>-${M_PI}</min_angle>
                <max_angle>${M_PI}</max_angle>
              </horizontal>
              <vertical>
                <samples>16</samples>
                <resolution>1</resolution>
                <min_angle>-${15.0*M_PI/180.0}</min_angle>
                <max_angle>${15.0*M_PI/180.0}</max_angle>
              </vertical>
            </scan>
            <range>
              <min>0.3</min>
              <max>131.0</max>
              <resolution>0.001</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.0</stddev>
            </noise>
          </ray>
          <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_velodyne_laser.so">
                <ros>
                    <argument>~/out:=velodyne_points</argument>
                </ros>
                <output_type>sensor_msgs/PointCloud2</output_type>
            <min_range>0.9</min_range>
            <max_range>130.0</max_range>
            <gaussianNoise>0.008</gaussianNoise>
          </plugin>
        </sensor>
    </gazebo>

</robot>
